repos:
  - repo: https://github.com/awebdeveloper/pre-commit-prettier
    rev: c0573b2f7c5f39fddf1c5b8b4528cc73686df524
    hooks:
      - id: prettier
        args: [] #list of args like "--single-quote", "--jsx-bracket-same-line", "--print-width 120", "--no-bracket-spacing"
        additional_dependencies: ["prettier@1.1.0"]
